### ISSUE TITLE
Not an issue. 

### ISSUE THREAD

**Issue by rj2764** [feram18/led-stock-ticker#14]
What is the smallest raspi you can use for this project? Can you use sports tickers as well?

Thanks

**Comment by feram18** [comment]
> What is the smallest raspi you can use for this project?

Personally I have setups with a Raspberry Pi 3B+ and 4B (2GB and 8GB models). I am aware of others that are able to run it on a [Zero 2 W](https://www.adafruit.com/product/5291), which would be the cheapest. But due to the chip shortage, older Raspberry Pi's might be more difficult to find than the latest 4B models. The cheapest would be the [4B 1GB of RAM model](https://www.adafruit.com/product/4295).

> Can you use sports tickers as well?

Yes, you should be able to use sports tickers on the same setup. I personally use the MLB and NHL scoreboards on my setups.
