### ISSUE TITLE
Stock ticker stuck on load screen

### ISSUE THREAD

**Issue by copyfile** [feram18/led-stock-ticker#24]
Since some time I'm using the led stock ticker and I really love it! As my PI sometimes is not loading good anymore I have  cronjob to restart every day. After the restart it runs a launcher.sh script with the following code. This was working until a couple of weeks ago, but now it is stuck on the screen with the version number (0.3.11). When I run the startup python myself it's working so I'm not sure what's happening. Any idea how I can fix this, or get the same result another way?

cd /
cd home/pi/led-stock-ticker
sudo python3 main.py --led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=2 --led-brightness=30

**Comment by feram18** [comment]
I'm thinking it may be starting up to quick, before the pi has connected to your network and it's not able to fetch data from the API and then crashing.

Using a `systemd` service might solve your issue as it can be configured so that it starts up a service (the project) after it has connected to the network. I provided an example on how I personally use one [here](https://github.com/feram18/led-stock-ticker/issues/25#issuecomment-1597605382).
